export const mockedResponse = [
	{
		id: 261392630,
		name: 'accompanist',
		full_name: 'google/accompanist',
		stargazers_count: 7261,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description: 'A collection of extension libraries for Jetpack Compose',
		fork: false,
		url: 'https://api.github.com/repos/google/accompanist',
		created_at: '2020-05-05T07:48:10.000Z',
		updated_at: '2024-05-28T06:20:10.000Z',
		pushed_at: '2024-05-17T22:39:47.000Z',
		git_url: 'git://github.com/google/accompanist.git',
		clone_url: 'https://github.com/google/accompanist.git',
		homepage: 'https://google.github.io/accompanist',
		size: 55907,
		watchers_count: 7261,
		language: 'Kotlin',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: false,
		has_pages: true,
		has_discussions: false,
		forks_count: 587,
		archived: false,
		disabled: false,
		open_issues_count: 5,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: ['android-library', 'jetpack-compose'],
		visibility: 'public',
		forks: 587,
		open_issues: 5,
		watchers: 7261,
		default_branch: 'main',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 106029625,
		name: 'active-learning',
		full_name: 'google/active-learning',
		stargazers_count: 1094,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description: null,
		fork: false,
		url: 'https://api.github.com/repos/google/active-learning',
		created_at: '2017-10-06T17:02:13.000Z',
		updated_at: '2024-05-24T16:24:15.000Z',
		pushed_at: '2022-12-05T01:29:18.000Z',
		git_url: 'git://github.com/google/active-learning.git',
		clone_url: 'https://github.com/google/active-learning.git',
		homepage: null,
		size: 55,
		watchers_count: 1094,
		language: 'Python',
		has_issues: false,
		has_projects: true,
		has_downloads: false,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 207,
		archived: false,
		disabled: false,
		open_issues_count: 2,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: [],
		visibility: 'public',
		forks: 207,
		open_issues: 2,
		watchers: 1094,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 23320304,
		name: 'adb-sync',
		full_name: 'google/adb-sync',
		stargazers_count: 1076,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description: null,
		fork: false,
		url: 'https://api.github.com/repos/google/adb-sync',
		created_at: '2014-08-25T16:18:51.000Z',
		updated_at: '2024-05-05T02:01:59.000Z',
		pushed_at: '2024-03-23T10:35:07.000Z',
		git_url: 'git://github.com/google/adb-sync.git',
		clone_url: 'https://github.com/google/adb-sync.git',
		homepage: null,
		size: 35,
		watchers_count: 1076,
		language: 'Python',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 165,
		archived: false,
		disabled: false,
		open_issues_count: 28,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: [],
		visibility: 'public',
		forks: 165,
		open_issues: 28,
		watchers: 1076,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 62048325,
		name: 'addlicense',
		full_name: 'google/addlicense',
		stargazers_count: 674,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description:
			'A program which ensures source code files have copyright license headers by scanning directory patterns recursively',
		fork: false,
		url: 'https://api.github.com/repos/google/addlicense',
		created_at: '2016-06-27T10:37:54.000Z',
		updated_at: '2024-05-28T21:12:32.000Z',
		pushed_at: '2024-01-18T20:05:42.000Z',
		git_url: 'git://github.com/google/addlicense.git',
		clone_url: 'https://github.com/google/addlicense.git',
		homepage: '',
		size: 112,
		watchers_count: 674,
		language: 'Go',
		has_issues: true,
		has_projects: false,
		has_downloads: false,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 168,
		archived: false,
		disabled: false,
		open_issues_count: 49,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: ['license', 'utility'],
		visibility: 'public',
		forks: 168,
		open_issues: 49,
		watchers: 674,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 42338931,
		name: 'Accessibility-Test-Framework-for-Android',
		full_name: 'google/Accessibility-Test-Framework-for-Android',
		stargazers_count: 443,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description: 'Accessibility checks for automated Android testing',
		fork: false,
		url: 'https://api.github.com/repos/google/Accessibility-Test-Framework-for-Android',
		created_at: '2015-09-12T00:49:01.000Z',
		updated_at: '2024-05-23T11:51:43.000Z',
		pushed_at: '2024-04-03T11:08:51.000Z',
		git_url:
			'git://github.com/google/Accessibility-Test-Framework-for-Android.git',
		clone_url:
			'https://github.com/google/Accessibility-Test-Framework-for-Android.git',
		homepage: '',
		size: 1154,
		watchers_count: 443,
		language: 'Java',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 124,
		archived: false,
		disabled: false,
		open_issues_count: 17,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: ['accessibility', 'android'],
		visibility: 'public',
		forks: 124,
		open_issues: 17,
		watchers: 443,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 46423194,
		name: 'acme',
		full_name: 'google/acme',
		stargazers_count: 379,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description: 'A simple ACME command line tool without 3rd party deps!',
		fork: false,
		url: 'https://api.github.com/repos/google/acme',
		created_at: '2015-11-18T14:14:40.000Z',
		updated_at: '2024-04-01T18:16:59.000Z',
		pushed_at: '2017-10-04T07:09:07.000Z',
		git_url: 'git://github.com/google/acme.git',
		clone_url: 'https://github.com/google/acme.git',
		homepage: '',
		size: 149,
		watchers_count: 379,
		language: 'Go',
		has_issues: true,
		has_projects: true,
		has_downloads: false,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 51,
		archived: true,
		disabled: false,
		open_issues_count: 23,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: [],
		visibility: 'public',
		forks: 51,
		open_issues: 23,
		watchers: 379,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 140437270,
		name: 'active-qa',
		full_name: 'google/active-qa',
		stargazers_count: 344,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description: null,
		fork: false,
		url: 'https://api.github.com/repos/google/active-qa',
		created_at: '2018-07-10T13:35:27.000Z',
		updated_at: '2024-05-11T05:21:38.000Z',
		pushed_at: '2018-12-11T15:39:52.000Z',
		git_url: 'git://github.com/google/active-qa.git',
		clone_url: 'https://github.com/google/active-qa.git',
		homepage: null,
		size: 88511,
		watchers_count: 344,
		language: 'Python',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 65,
		archived: true,
		disabled: false,
		open_issues_count: 13,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: [],
		visibility: 'public',
		forks: 65,
		open_issues: 13,
		watchers: 344,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 52811542,
		name: 'access-bridge-explorer',
		full_name: 'google/access-bridge-explorer',
		stargazers_count: 113,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description:
			'Explore accessibility tree of Java Access Bridge enabled applications',
		fork: false,
		url: 'https://api.github.com/repos/google/access-bridge-explorer',
		created_at: '2016-02-29T17:56:59.000Z',
		updated_at: '2024-05-05T06:10:46.000Z',
		pushed_at: '2016-06-27T22:24:12.000Z',
		git_url: 'git://github.com/google/access-bridge-explorer.git',
		clone_url: 'https://github.com/google/access-bridge-explorer.git',
		homepage: '',
		size: 716,
		watchers_count: 113,
		language: 'C#',
		has_issues: true,
		has_projects: true,
		has_downloads: false,
		has_wiki: false,
		has_pages: true,
		has_discussions: false,
		forks_count: 50,
		archived: true,
		disabled: false,
		open_issues_count: 21,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: [],
		visibility: 'public',
		forks: 50,
		open_issues: 21,
		watchers: 113,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 170908616,
		name: '.github',
		full_name: 'google/.github',
		stargazers_count: 86,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description: 'default configuration for @google repos',
		fork: false,
		url: 'https://api.github.com/repos/google/.github',
		created_at: '2019-02-15T18:14:38.000Z',
		updated_at: '2024-05-06T15:10:01.000Z',
		pushed_at: '2024-02-26T06:56:48.000Z',
		git_url: 'git://github.com/google/.github.git',
		clone_url: 'https://github.com/google/.github.git',
		homepage: '',
		size: 6,
		watchers_count: 86,
		language: null,
		has_issues: true,
		has_projects: false,
		has_downloads: true,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 244,
		archived: false,
		disabled: false,
		open_issues_count: 14,
		license: {},
		allow_forking: true,
		is_template: false,
		topics: [],
		visibility: 'public',
		forks: 244,
		open_issues: 14,
		watchers: 86,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
	{
		id: 259457077,
		name: 'abstracttext',
		full_name: 'google/abstracttext',
		stargazers_count: 77,
		owner: {
			login: 'google',
			id: 1342004,
			avatar_url: 'https://avatars.githubusercontent.com/u/1342004?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/google',
			type: 'Organization',
			site_admin: false,
		},
		private: false,
		description:
			'MediaWiki extension to handle multilingual abstract content',
		fork: false,
		url: 'https://api.github.com/repos/google/abstracttext',
		created_at: '2020-04-27T21:13:10.000Z',
		updated_at: '2024-02-28T23:44:57.000Z',
		pushed_at: '2024-03-12T17:02:14.000Z',
		git_url: 'git://github.com/google/abstracttext.git',
		clone_url: 'https://github.com/google/abstracttext.git',
		homepage: '',
		size: 1818,
		watchers_count: 77,
		language: 'JavaScript',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 10,
		archived: false,
		disabled: false,
		open_issues_count: 20,
		license: {
			key: 'apache-2.0',
			name: 'Apache License 2.0',
			spdx_id: 'Apache-2.0',
			url: 'https://api.github.com/licenses/apache-2.0',
		},
		allow_forking: true,
		is_template: false,
		topics: [
			'internationalization',
			'mediawiki-extension',
			'multilingual',
			'nlg',
		],
		visibility: 'public',
		forks: 10,
		open_issues: 20,
		watchers: 77,
		default_branch: 'master',
		permissions: {
			admin: false,
			maintain: false,
			push: false,
			triage: false,
			pull: true,
		},
	},
];
